defmodule LiveQuizWeb.ApiSpecTest do
  @moduledoc """
  Contract test of the OpenAPI specification.

  The specification is derived from the router and from the `operation/2`
  annotations of the controllers, so a route added without its annotation — or
  an annotation that stops matching what the API answers — fails here instead of
  drifting silently.
  """

  use LiveQuizWeb.ConnCase, async: true

  alias LiveQuizWeb.ApiSpec

  @authenticated_operations [
    {"/api/v1/session", "delete"},
    {"/api/v1/me", "get"},
    {"/api/v1/quizzes", "get"},
    {"/api/v1/quizzes", "post"},
    {"/api/v1/quizzes/{id}", "get"},
    {"/api/v1/quizzes/{id}", "put"},
    {"/api/v1/quizzes/{id}", "patch"},
    {"/api/v1/quizzes/{id}", "delete"},
    {"/api/v1/quizzes/{quiz_id}/questions", "get"},
    {"/api/v1/quizzes/{quiz_id}/questions", "post"},
    {"/api/v1/quizzes/{quiz_id}/questions/{id}", "get"},
    {"/api/v1/quizzes/{quiz_id}/questions/{id}", "put"},
    {"/api/v1/quizzes/{quiz_id}/questions/{id}", "patch"},
    {"/api/v1/quizzes/{quiz_id}/questions/{id}", "delete"},
    {"/api/v1/quizzes/{quiz_id}/questions/{id}/move", "patch"}
  ]

  @public_operations [
    {"/api/v1/session", "post"},
    {"/api/v1/session/refresh", "post"}
  ]

  describe "GET /api/openapi" do
    test "answers 200 with an OpenAPI 3 document", %{conn: conn} do
      spec = conn |> get(~p"/api/openapi") |> json_response(200)

      assert String.starts_with?(spec["openapi"], "3.")
      assert spec["info"]["title"] == "Live Quiz API"
      assert spec["info"]["version"] == "1.0.0"
      assert is_map(spec["paths"])
    end

    test "does not require authentication", %{conn: conn} do
      assert build_conn() |> get(~p"/api/openapi") |> json_response(200)
      assert conn |> get(~p"/api/openapi") |> json_response(200)
    end

    test "documents every implemented path", %{conn: conn} do
      spec = conn |> get(~p"/api/openapi") |> json_response(200)

      documented = @authenticated_operations ++ @public_operations

      for {path, verb} <- documented do
        assert %{"summary" => summary} = spec["paths"][path][verb]
        assert is_binary(summary)
      end

      assert Map.keys(spec["paths"]) |> Enum.sort() ==
               documented |> Enum.map(&elem(&1, 0)) |> Enum.uniq() |> Enum.sort()
    end
  end

  describe "specification" do
    test "is generated by to_map/1 without raising" do
      map = ApiSpec.spec() |> OpenApiSpex.OpenApi.to_map()

      assert is_map(map["paths"])
      assert is_map(map["components"]["schemas"])
      assert Jason.encode!(map) =~ "Live Quiz API"
    end

    test "declares the bearerAuth security scheme", %{conn: conn} do
      spec = conn |> get(~p"/api/openapi") |> json_response(200)

      assert spec["components"]["securitySchemes"]["bearerAuth"]["type"] == "http"
      assert spec["components"]["securitySchemes"]["bearerAuth"]["scheme"] == "bearer"
      assert spec["components"]["securitySchemes"]["bearerAuth"]["bearerFormat"] == "JWT"
      assert spec["security"] == [%{"bearerAuth" => []}]
    end

    test "requires bearerAuth on every authenticated operation", %{conn: conn} do
      spec = conn |> get(~p"/api/openapi") |> json_response(200)

      for {path, verb} <- @authenticated_operations do
        assert spec["paths"][path][verb]["security"] == [%{"bearerAuth" => []}],
               "#{String.upcase(verb)} #{path} deveria exigir bearerAuth"
      end
    end

    test "exempts login and refresh from bearerAuth", %{conn: conn} do
      spec = conn |> get(~p"/api/openapi") |> json_response(200)

      for {path, verb} <- @public_operations do
        assert spec["paths"][path][verb]["security"] == [],
               "#{String.upcase(verb)} #{path} não deveria exigir bearerAuth"
      end
    end

    test "groups the operations by tag", %{conn: conn} do
      spec = conn |> get(~p"/api/openapi") |> json_response(200)

      assert Enum.map(spec["tags"], & &1["name"]) == ["Sessão", "Quizzes", "Perguntas"]
      assert spec["paths"]["/api/v1/me"]["get"]["tags"] == ["Sessão"]
      assert spec["paths"]["/api/v1/quizzes"]["get"]["tags"] == ["Quizzes"]
      assert spec["paths"]["/api/v1/quizzes/{quiz_id}/questions"]["get"]["tags"] == ["Perguntas"]
    end

    test "documents 201, 401, 404, 409 and 422 on the creation of a question", %{conn: conn} do
      spec = conn |> get(~p"/api/openapi") |> json_response(200)

      responses = spec["paths"]["/api/v1/quizzes/{quiz_id}/questions"]["post"]["responses"]

      assert Enum.sort(Map.keys(responses)) == ["201", "401", "404", "409", "422"]

      for {_status, response} <- responses do
        assert is_binary(response["description"])
      end
    end

    test "documents the pagination of the quiz listing", %{conn: conn} do
      spec = conn |> get(~p"/api/openapi") |> json_response(200)

      operation = spec["paths"]["/api/v1/quizzes"]["get"]

      assert Enum.map(operation["parameters"], & &1["name"]) == ["page", "per_page", "search"]

      for parameter <- operation["parameters"] do
        assert parameter["in"] == "query"
        assert is_binary(parameter["description"])
      end

      assert operation["responses"]["200"]["content"]["application/json"]["schema"] == %{
               "$ref" => "#/components/schemas/QuizListResponse"
             }

      assert %{"$ref" => "#/components/schemas/PaginationMeta"} =
               spec["components"]["schemas"]["QuizListResponse"]["properties"]["meta"]
    end

    test "gives every schema a description and an example", %{conn: conn} do
      spec = conn |> get(~p"/api/openapi") |> json_response(200)

      schemas = spec["components"]["schemas"]

      assert map_size(schemas) == 18

      for {name, schema} <- schemas do
        assert is_binary(schema["description"]), "schema #{name} está sem description"
        assert schema["example"], "schema #{name} está sem example"
      end
    end
  end

  describe "GET /api/docs" do
    test "answers 200 with the Swagger UI", %{conn: conn} do
      html = conn |> get(~p"/api/docs") |> html_response(200)

      assert html =~ "SwaggerUIBundle"
      assert html =~ "/api/openapi"
    end
  end
end
