import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :live_quiz, LiveQuizWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :live_quiz, LiveQuizWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Every cookie this application writes carries a credential: the session, the
# participation of a guest, and the fourteen day remember-me. `force_ssl` above
# already keeps a browser on https, but the flag is the one protection that does
# not depend on the rest being right — the first request a browser makes before
# it has seen the HSTS header still sends the cookies it already holds.
#
# It is on here and nowhere else: over http, which is what development and the
# test suite serve, a secure cookie is one the browser never sends back.
config :live_quiz, :secure_cookies, true

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
